/**
 * PDF Export Utility
 * Uses jsPDF to export business plans, SWOT analyses, and pitch decks.
 * Install: npm install jspdf
 */

export async function exportBusinessPlanPDF(sections: { title: string; content?: string; keyPoints?: string[] }[]) {
  const { jsPDF } = await import('jspdf')
  const doc = new jsPDF()

  const primaryColor = [124, 58, 237] as [number, number, number] // Purple
  const textColor = [30, 30, 50] as [number, number, number]
  const mutedColor = [100, 100, 120] as [number, number, number]

  let y = 20

  // Title
  doc.setFontSize(24)
  doc.setTextColor(...primaryColor)
  doc.text('Business Plan', 20, y)
  y += 8

  doc.setFontSize(10)
  doc.setTextColor(...mutedColor)
  doc.text(`Generated by StartupAdvisor AI · ${new Date().toLocaleDateString()}`, 20, y)
  y += 15

  // Divider
  doc.setDrawColor(...primaryColor)
  doc.setLineWidth(0.5)
  doc.line(20, y, 190, y)
  y += 10

  for (const section of sections) {
    if (y > 260) {
      doc.addPage()
      y = 20
    }

    // Section title
    doc.setFontSize(14)
    doc.setTextColor(...primaryColor)
    doc.text(section.title, 20, y)
    y += 7

    // Content
    if (section.content) {
      doc.setFontSize(10)
      doc.setTextColor(...textColor)
      const lines = doc.splitTextToSize(section.content, 170)
      doc.text(lines, 20, y)
      y += lines.length * 5 + 5
    }

    // Key points
    if (section.keyPoints) {
      doc.setFontSize(10)
      doc.setTextColor(...textColor)
      for (const point of section.keyPoints) {
        if (y > 270) { doc.addPage(); y = 20 }
        doc.text(`• ${point}`, 25, y)
        y += 5
      }
      y += 5
    }

    y += 5
  }

  doc.save('StartupAdvisor-Business-Plan.pdf')
}

export async function exportSWOTPDF(swotItems: Record<string, string[]>) {
  const { jsPDF } = await import('jspdf')
  const doc = new jsPDF()

  const categories = [
    { key: 'strengths', label: 'Strengths', color: [16, 185, 129] as [number, number, number] },
    { key: 'weaknesses', label: 'Weaknesses', color: [239, 68, 68] as [number, number, number] },
    { key: 'opportunities', label: 'Opportunities', color: [37, 99, 235] as [number, number, number] },
    { key: 'threats', label: 'Threats', color: [245, 158, 11] as [number, number, number] },
  ]

  doc.setFontSize(22)
  doc.setTextColor(124, 58, 237)
  doc.text('SWOT Analysis', 20, 20)

  doc.setFontSize(10)
  doc.setTextColor(100, 100, 120)
  doc.text(`StartupAdvisor AI · ${new Date().toLocaleDateString()}`, 20, 28)

  let y = 40

  for (const cat of categories) {
    doc.setFontSize(13)
    doc.setTextColor(...cat.color)
    doc.text(cat.label, 20, y)
    y += 6

    doc.setFontSize(10)
    doc.setTextColor(30, 30, 50)
    for (const item of swotItems[cat.key] ?? []) {
      doc.text(`• ${item}`, 25, y)
      y += 5
    }
    y += 8
  }

  doc.save('StartupAdvisor-SWOT.pdf')
}
